[package]
name = "rocket_test1"
version = "0.1.0"
authors = ["shin.takahashi <shin.takahashi@fintertech.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4"
rocket_contrib = "0.4"
serde = "1.0"
